enum userType {
    organization
    consumer
    vendor
}
type User {
    email: String! @unique
    name: String!
    orgName: String
    type: userType!
    adhaar: AdhaarInfo @relation
}
type AdhaarInfo {
    aadharNumber: String!
    address: String!
    DOB: String!
    owner: User!
}
type Query {
    adhaar: AdhaarInfo
}